### ISSUE TITLE
Laravel throws 404 on site 

### ISSUE THREAD

**Issue by SilvioMarijic** [redbaron76/PongoCMS-Laravel-cms-bundle#18]
Hi , ive installed the pongo cms on laravel ( i folowd the guide from pongocms.com ) and when the cms::setup finishes i got message to visit my site at http://localhost/laravel/public, when i navigate to that url Laravel gives me 404 but i when i point my browser to http://localhost/laravel/public/home  it works

**Comment by ptim** [comment]
I'm having a similar problem: 

I've installed in pongo.dev locally on XAMPP, and have battled past the mysql socket issue with XAMPP.  Pongo reported installing correctly, and I can login and edit blog posts at /cms, but I get a 404 at:
- /  
- /home
- /blog 
- /blog/blog-post 

there are no errors in my log... my bundles.php file is a cut and paste from the pongo homepage, and my routes file was completely commented out... if i add a route for / then my little comment displays...

I'm at a loss! any suggestions?

The pongo readme displays 1.2 - RC1

**Comment by redbaron76** [comment]
Please update PongoCMS to last version.
Found and resolved some issues on Windows environment.

php artisan cms::backup update

**Comment by ptim** [comment]
Tx @redbaron76 ..

I started over, and found some steps not mentioned in the install guide:
- get laravel working
- run `php artisan migrate:install`
- install Pongo using `php artisan bundle:install pongocms`
- edit bundles.php as instructed
- run `php artisan cms:setup`

Now Pongo is running smoothly!

Whether or not step 2 is absolutely necessary, I don't know, but it did highlight the error:

`Warning: PDO::__construct(): [2002] No such file or directory (trying to connect via unix:///Applications/XAMPP/xamppfiles/var/mysql/mysql.sock ) in /Users/timosborn/Sites/pongo.dev/laravel/database/connectors/mysql.php on line 33`

This issue is discussed here: [Laravel - setting up migrations](http://forums.laravel.io/viewtopic.php?pid=26423)
Adding a symlink as described worked for me (adding the 'unix_socket' db configuration didn't).

Mac 10.8.2 
XAMPP 1.7.3 
Laravel 3.2.13
PongoCMS 1.2 RC1

**Comment by redbaron76** [comment]
That sounds strange.
PongoCMS setup task already performs a "php artisan migrate:install" behind the scenes.

I think this issue could be related to that sock issue you highlight in the forum, probably external to and "above" of PongoCMS bundle itself.

Anyway thanks for reporting this.

**Comment by 725Productions** [comment]
Hi, I'm running Ubuntu/Nginx.  I am seeing a 404 at '/' of my site, but /cms work great.  

I saw your fix here, in this thread:
"Please update PongoCMS to last version.
Found and resolved some issues on Windows environment.

php artisan cms::backup update"

I tried all of these... no success.  I used artisan to install.  What am I doing wrong?

**Comment by ptim** [comment]
@joe-3coast 
My issue was resolved by doing a `php artisan migrate:install` before installing pongo.. 
see my comment above - good luck!

**Comment by 725Productions** [comment]
ptim - thx for your reply.  Actually I found that my issue was caused by not setting a url in my application.php config file.  The base Laravel install does not require it, but PongoCMS does; therefore I never put in before.  Mostly because I'm not that experienced yet... But I digress, now I have this 404 problem solved, on the next problem: all my images servers with /cms/image/resize are return with 404.  Troubleshooting fun!!

**Comment by ptim** [comment]
lol! best wishes :)

**Comment by justmyfreak** [comment]
thanks @joe-3coast it works :)

**Comment by gnarlymedia** [comment]
Has anyone had further joy with this issue? I've tried the steps mentioned above (running: php artisan migrate:install) and this doesn't resolve my Server Error: 404 (Not Found) error when I go to URL for the frontend. All the installations seemed to have completed successfully. I also get a Not Found going to /cms. I have included a URL in my laravel config... I have tried everything and I'm at the end of my tether with Pongo CMS! Please help :-)

Mac OS 10.7.5
Default OS Apache install
MySQL Server
PHP 5.3.15

**Comment by justmyfreak** [comment]
Have you set up application url in setting?

**Comment by gnarlymedia** [comment]
Hi there, yes I have, I put 'http://localhost/~[myusername]/pongo-1/public' - do you know if I'm supposed to put this or the project root ie 'http://localhost/~[myusername]/pongo-1/'?

**Comment by gnarlymedia** [comment]
Also, I've noticed that in the config that goes into bundles.php, the two lines:

```
            //CMS METHODS
            'CmsRender'                 => '(:bundle)/libraries/render.php',
            'CmsUtility'                => '(:bundle)/libraries/utilities.php',
```

don't match with with the filenames in those folders which are 'cmsrender.php' and 'cmsutility.php'. Changing either one to match the other before running 'php artisan cms::setup' doesn't seem to help any.

Also, curiously, the setup seems to remove those lines in bundles.php.

Does anyone know if that would affect it? Thanks

**Comment by justmyfreak** [comment]
I thing you have to setup into something like http://pongo.dev.
It worked for me

**Comment by gnarlymedia** [comment]
Ah, are you using something like MAMP or XAMPP?

**Comment by justmyfreak** [comment]
XAMPP on windows

**Comment by govereem** [comment]
I had the 404 pages also, I did all the suggestions that where stated before but the problem was in the application/config/application.php i had to change 'index' => 'index.php', to 'index' => '', The system is searching for /home in the pongo_pages tables but uses the full path to search for it so it will never find the needed page. I hope this helps someone.

**Comment by gnarlymedia** [comment]
Thanks so much @govereem! That fixed my problem in one step! Very much appreciated, hope you have good luck. Cheers Simon

**Comment by WayneDV** [comment]
I fired up a fresh cloud server for my first PongoCMS installation and also got the 404 errors when trying to access /cms ; /blogs ; etc.   In my case the problem was that the server image did not have Apache's mod_rewrite enabled by default.
